# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('year_published', models.CharField(max_length=10)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('description', models.TextField()),
                ('greek_rating', models.FloatField()),
                ('average_rating', models.FloatField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
