# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgame',
            old_name='greek_rating',
            new_name='geek_rating',
        ),
    ]
