# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180128_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardgame',
            unique_together=set([('name', 'year_published')]),
        ),
    ]
