# Generated by Django 2.0.3 on 2018-03-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickstarters', '0002_kickstarter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickstarter',
            name='sort_category',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
