# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180128_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
